### ISSUE TITLE
Generate documentation / 1 pager for Direct on tech selection

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#39]
For use by our direct liaison, POs, TL, others to explain selections, criteria, etc.

**Comment by cmh2166** [comment]
See #35

**Comment by jcoyne** [comment]
Notes:

Functional Reactive Programming (FRP) backend.  "strong affinity with high-performance, concurrency, asynchronous operations and non-blocking IO." -- https://spring.io/blog/2016/06/07/notes-on-reactive-programming-part-i-the-reactive-landscape

Language choice cannot be decoupled from Framework choice. We wanted to focus on APIs. Rails is particularly heavy -- focusing on HTML based applications rather than APIs. Swagger allows us to use documentation driven design.  The go-swagger library seemed particularly active. 

Performance is important, Ruby is slow.  Go is faster in Java  on many benchmarks https://benchmarksgame.alioth.debian.org/u64q/go.html. Go is an order of magnitude faster than Ruby on Rails http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/

Developer happiness -- Go isn't too far of a change for a ruby developer .  Doesn't require a complex IDE (as java does).  Has free developer tools (for Atom).

Cloud support -- Go fits in very well into the Docker ecosystem.  It's also one of the first class languages on AWS (Ruby is not)

**Comment by cmh2166** [comment]
In progress here: https://docs.google.com/document/d/1joQNK1aM0z6bJEC-f1LpcwFF2sJKumLeU2Q7ugBqX5I/edit#heading=h.iaqvlzisu6am

**Comment by cmh2166** [comment]
done, in a wiki page: https://github.com/sul-dlss-labs/taco/wiki/TACO-Technology-Selection-Info-Page

became a wiki page + a slidedeck, will check with management to see if a 1 pager is needed.
